### ISSUE TITLE
Dockerbeat & Logstash

### ISSUE THREAD

**Issue by danbrab** [Ingensi/dockerbeat#106]
Hello,

i installed igensi/dockerbeat on my docker-server (10.10.0.1). How can i connect it with my logstash-server (10.10.0.2)?

dockerbeat.yml:

-------------------------

dockerbeat:
  period: ${PERIOD:5}
  socket: ${DOCKER_SOCKET:unix:///var/run/docker.sock}
  tls:
    enable: ${DOCKER_ENABLE_TLS:false}
    ca_path: ${DOCKER_CA_PATH}
    cert_path: ${DOCKER_CERT_PATH}
    key_path: ${DOCKER_KEY_PATH}
output:
  logstash:
    hosts: ["10.10.0.2:5044"]
    tls:
      certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]

--------------------------

Thanks

**Comment by marminthibaut** [comment]
Hi,

1 - don't forget to format your file as yml.
2 - check your logstash input configuration

I think that it is a libbeat issue. Don't forget to check the libbeat version used by dockerbeat (in the `glide.yaml` file).

**Comment by urso** [comment]
Any log output when configuring info level? Logstash config looks ok, besides potential problems with formatting or invalid certificate (e.g. domain/ip in certificate does not match logstash endpoint). Is TLS properly configured in beats input plugin?

**Comment by danbrab** [comment]
Topbeat and packetbeat are running. It's not connection or certificate problem. And i don't forgot to format dockerbeat.yml as yml.

When i start with: 
de@dockb:/usr/local/work/src/github.com/ingensi/dockerbeat$ ./dockerbeat -v -e -c dockerbeat.yml

2016/06/21 13:02:26.206547 beat.go:222: DBG  Initializing output plugins
2016/06/21 13:02:26.206653 geolite.go:24: INFO GeoIP disabled: No paths were set under shipper.geoip.paths
2016/06/21 13:02:26.207638 logstash.go:77: INFO Max Retries set to: 3
2016/06/21 13:02:26.207713 sync.go:63: DBG  connect
2016/06/21 13:02:26.281839 outputs.go:87: INFO Activated logstash as output plugin.
2016/06/21 13:02:26.281922 publish.go:231: DBG  Create output worker
2016/06/21 13:02:26.282069 publish.go:273: DBG  No output is defined to store the topology. The server fields might not be filled.
2016/06/21 13:02:26.282167 publish.go:287: INFO Publisher name: dockb
2016/06/21 13:02:26.282624 async.go:70: INFO Flush Interval set to: 277777h46m40s
2016/06/21 13:02:26.282662 async.go:71: INFO Max Bulk Size set to: 2048
2016/06/21 13:02:26.282681 async.go:79: DBG  create bulk processing worker (interval=277777h46m40s, bulk size=2048)
2016/06/21 13:02:26.282793 filter.go:41: DBG  configuration []
2016/06/21 13:02:26.282898 filter.go:52: DBG  filters: 
2016/06/21 13:02:26.282978 beat.go:245: INFO Init Beat: dockerbeat; Version: 1.0.0-rc1
2016/06/21 13:02:26.282999 beat.go:246: INFO Filter 
2016/06/21 13:02:26.283142 cfgfile.go:89: INFO Replacing config environment variable '${PERIOD}' with default '5'
2016/06/21 13:02:26.283179 cfgfile.go:89: INFO Replacing config environment variable '${DOCKER_SOCKET}' with default 'unix:///var/run/docker.sock'
2016/06/21 13:02:26.283197 cfgfile.go:89: INFO Replacing config environment variable '${DOCKER_ENABLE_TLS}' with default 'false'
2016/06/21 13:02:26.283214 cfgfile.go:92: INFO Replacing config environment variable '${DOCKER_CA_PATH}' with ''
2016/06/21 13:02:26.283230 cfgfile.go:92: INFO Replacing config environment variable '${DOCKER_CERT_PATH}' with ''
2016/06/21 13:02:26.283247 cfgfile.go:92: INFO Replacing config environment variable '${DOCKER_KEY_PATH}' with ''
2016/06/21 13:02:26.283917 dockerbeat.go:111: INFO dockerbeat%!(EXTRA string=Init dockerbeat)
2016/06/21 13:02:26.283957 dockerbeat.go:112: INFO dockerbeat%!(EXTRA string=Follow docker socket %q
, string=unix:///var/run/docker.sock)
2016/06/21 13:02:26.283989 dockerbeat.go:116: INFO dockerbeat%!(EXTRA string=TLS disabled
)
2016/06/21 13:02:26.284027 dockerbeat.go:118: INFO dockerbeat%!(EXTRA string=Period %v
, time.Duration=5s)
2016/06/21 13:02:26.284397 beat.go:275: INFO dockerbeat sucessfully setup. Start running.
2016/06/21 13:02:26.284544 dockerbeat.go:162: INFO dockerbeat is running! Hit CTRL-C to stop it.
2016/06/21 13:02:32.818583 event.go:21: WARN unmarshal err: %!v(MISSING)
2016/06/21 13:02:32.818623 event.go:75: WARN fail to marschall & unmarshall struct created
2016/06/21 13:02:32.818792 client.go:193: DBG  Publish: {
  "@timestamp": "2016-06-21T13:02:32.000Z",
  "beat": {
    "hostname": "dockb",
    "name": "dockb"
  },
  "container": {
    "command": "/bin/bash",
    "created": "2016-06-21T15:00:48+02:00",
    "id": "b664b52cdca1f872612a95b765d1d65ba97cca2e4515800eb7c535575d6e2a61",
    "image": "ubuntu:14.04",
    "names": [
      "/sick_sinoussi"
    ],
    "ports": [],
    "sizeRootFs": 0,
    "sizeRw": 0,
    "status": "Up About a minute"
  },
  "containerID": "b664b52cdca1f872612a95b765d1d65ba97cca2e4515800eb7c535575d6e2a61",
  "containerLabels": [],
  "containerName": "sick_sinoussi",
  "dockerSocket": "unix:///var/run/docker.sock",
  "type": "container"
}
2016/06/21 13:02:32.818919 client.go:193: DBG  Publish: {
  "@timestamp": "2016-06-21T13:02:32.000Z",
  "beat": {
    "hostname": "dockb",
    "name": "dockb"
  },
  "containerID": "b664b52cdca1f872612a95b765d1d65ba97cca2e4515800eb7c535575d6e2a61",
  "containerLabels": [],
  "containerName": "sick_sinoussi",
  "cpu": {
    "percpuUsage": {
      "cpu0": 0,
      "cpu1": 0.000223865
    },
    "totalUsage": 0.000223865,
    "usageInKernelmode": 0,
    "usageInUsermode": 0
  },
  "dockerSocket": "unix:///var/run/docker.sock",
  "type": "cpu"
}
2016/06/21 13:02:32.819023 client.go:193: DBG  Publish: {
  "@timestamp": "2016-06-21T13:02:32.000Z",
  "beat": {
    "hostname": "dockb",
    "name": "dockb"
  },
  "containerID": "b664b52cdca1f872612a95b765d1d65ba97cca2e4515800eb7c535575d6e2a61",
  "containerLabels": [],
  "containerName": "sick_sinoussi",
  "dockerSocket": "unix:///var/run/docker.sock",
  "memory": {
    "failcnt": 0,
    "limit": 3080466432,
    "maxUsage": 1310720,
    "totalRss": 622592,
    "totalRss_p": 0.00020210965246447458,
    "usage": 647168,
    "usage_p": 0.00021008766506175648
  },
  "type": "memory"
}
2016/06/21 13:02:32.819089 client.go:193: DBG  Publish: {
  "@timestamp": "2016-06-21T13:02:32.000Z",
  "beat": {
    "hostname": "dockb",
    "name": "dockb"
  },
  "blkio": {
    "read_ps": 0,
    "total_ps": 0,
    "write_ps": 0
  },
...
...
...

How can i compare libbeat version?

**Comment by ruflin** [comment]
A convenient option to compare is using Github. An example url for comparing master with the commit used currently by dockerbeat looks as following: https://github.com/elastic/beats/compare/05cd6641cf6e4fa12caa6e85588e181f8eefe1e6...master

**Comment by marminthibaut** [comment]
We are currently working on an update of the libbeat dependency. We will
set a tag matching a libbeat released version instead an anonymous revision
number ;)

**Comment by danbrab** [comment]
Thank you!!!

**Comment by danbrab** [comment]
Hi,
I need help again)))

I'm new in dockerworld and i don't understand with which command i can connect my servers.

what have i do?
$ docker network create dockernettest
...

docker-server (10.10.0.1)
logstash-server (10.10.0.2)
