### ISSUE TITLE
Add Option to Alter Field Names??

### ISSUE THREAD

**Issue by 326TimesBetter** [Ingensi/dockerbeat#108]
I see in your documentation, the fields produced by dockerbeats are named:
"container", "cpu", "net, "memory", "blkio", "log".

Some of these clash with types that I already process in logstash. Is there a way I can alter the names produced by dockerbeat (maybe simply prepent with 'docker_') to prevent this overlap??

Thanks!!

**Comment by gpolaert** [comment]
IMO, changing the field names directly from logstash (mutate) is better way.
You can add a tag to identify the beats.

**Comment by 326TimesBetter** [comment]
Yeah that worked great. Didn't know about the beats option to send tags with messages. Thanks!
