### ISSUE TITLE
Occasional MASSIVE cpu metrics??

### ISSUE THREAD

**Issue by 326TimesBetter** [Ingensi/dockerbeat#112]
Occasionally dockerbeat is throwing a log with cpu.totalUsage off of the charts. Like unrealistically high, representing more cpu than our memory has (knowing you get 100% per cpu).

Example:

![image](https://cloud.githubusercontent.com/assets/16246896/16818862/e78640b8-4917-11e6-80b2-312ac65b5357.png)

Have you guys seen this before or know what could cause something like this??

Thanks!

**Comment by tsg** [comment]
This looks quite similar to something we had in Topbeat, see this [PR](https://github.com/elastic/beats/pull/1928) that fixes it. The usage of unsigned integers caused small negative values to be transformed in huge positive values. 

Looking at the dockerbeat code, the same might be happening [here](https://github.com/Ingensi/dockerbeat/blob/develop/calculator/cpu.go#L39).

**Comment by 326TimesBetter** [comment]
Any update on this issue?? This is literally the only thing preventing us from utilizing this tool in production unfortunately :(

**Comment by marminthibaut** [comment]
I'll be on it on Thursday :racehorse:

**Comment by marminthibaut** [comment]
@326TimesBetter Can you check if this version of dockerbeat resolve your issue? If you don't want to compile dockerbeat yourselft, here is a compiled version for linux x86_64 architecture.

[dockerbeat.zip](https://github.com/Ingensi/dockerbeat/files/403483/dockerbeat.zip)

**Comment by marminthibaut** [comment]
@326TimesBetter ??
