### ISSUE TITLE
dash in container names do not work.

### ISSUE THREAD

**Issue by lesaux** [Ingensi/dockerbeat#122]
Say I have a container name with dashes:

r-load-balancer-ssl_load-balancer-ssl_2

I obtain 6 hosts in kibana. It seems a host is created after each dash.

**Comment by lesaux** [comment]
actually, the bug is only in the dockerbeats dashboards.

**Comment by lesaux** [comment]
Sorry I'm closing this. I was not using the proper mapping.

**Comment by marminthibaut** [comment]
Thanks no problem!
