### ISSUE TITLE
Percentage values should be set between 0 and 1

### ISSUE THREAD

**Issue by marminthibaut** [Ingensi/dockerbeat#36]
Currently, percentage values are set between 0 and 100, but kibana field format only supports percentages between 0 and 1 out of the box...

**Comment by marminthibaut** [comment]
@erwanncloarec go go go?

**Comment by erwanncloarec** [comment]
I'm on it

Le mer. 7 oct. 2015 16:13, Thibaut Marmin <notifications@github.com> a
écrit :

**Comment by marminthibaut** [comment]
:+1:

**Comment by marminthibaut** [comment]
Is it ready to merge?

**Comment by erwanncloarec** [comment]
Is there a way to tell Kibana that these are percentage? Like a bulk file to send to ES ?

**Comment by gpolaert** [comment]
Other question about cpu usage. Is the total cpu usage > 100 % like top or htop (100% x number of cpu) ?If it's not, may be we can divide the total per the number of cpu and provides the standard deviation in order to know if one processor is more used than an another.

**Comment by erwanncloarec** [comment]
I checked and it seems like 100% totalCPU means  that all the cores are used at 100%.
