### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by cmfatih** [Ingensi/dockerbeat#47]
Hi @marminthibaut 

Do you know ETA for next release?

**Comment by marminthibaut** [comment]
We are working on it this week. Can you help us?

**Comment by marminthibaut** [comment]
Next release will be a Beta 2 (see the milestone https://github.com/Ingensi/dockerbeat/milestones)

**Comment by cmfatih** [comment]
@marminthibaut : Really busy nowadays, but I will be using and contributing to the project once I settle it. Thanks for this OSS project :+1:

**Comment by marminthibaut** [comment]
Thanks :+1: !!
