### ISSUE TITLE
Should dockerbeat allow to monitor container logs?

### ISSUE THREAD

**Issue by marminthibaut** [Ingensi/dockerbeat#55]
The question is: Does the dockerbeat role is to monitor only container **statistics** or should also ship container **logs** ?

**Comment by erwanncloarec** [comment]
In my opinion, Dockerbeat is only about container stats. We can however create another libbeat project for the container logs.

**Comment by hmalphettes** [comment]
I was hoping it would monitor the logs too.

**Comment by pcallewaert** [comment]
Does this mean the logging driver of the container stays JSON?
We ship our logs now to logstash with docker 1.8's new feature, custom logging drivers. We use the GELF driver to ship it to logstash. The only disadvantage for us is this disables the docker logs command on the host itself..
If dockerbeat can overcome this issue it would be a big advantage!

**Comment by mrkschan** [comment]
FYI, there was a related discussion in libbeat https://github.com/elastic/libbeat/issues/37

**Comment by mrkschan** [comment]
And, this https://github.com/docker/docker/issues/14949

**Comment by marminthibaut** [comment]
I also think that Dockerbeat should **only ship data from Docker Stats API**. Container logs shipping should be managed either by a docker logging driver, or by simply log into files and ship logs with filebeat.

**Comment by ebuildy** [comment]
Only stat is enough ;-) 

There are already a ton of yet another Docker logs shipper (btw not so simple than dockerbeat I must admit ^^).

**Comment by Y4Rv1K** [comment]
Agreed with @erwanncloarec .

BTW did somebody start decent project? So we can use, test, contribute

**Comment by urso** [comment]
@urso I'm considering to enhance filebeat to support json input + docker id from location using the jsonlog driver with file-rotation.

**Comment by tymofii-polekhin** [comment]
@Y4Rv1K `docker engine --log-driver=journald` + https://github.com/mheese/journalbeat
