### ISSUE TITLE
Should Dockerbeat be able to monitor many docker daemons?

### ISSUE THREAD

**Issue by marminthibaut** [Ingensi/dockerbeat#59]
The question is: if we have many docker daemons to monitor, 

* should we have to launch **as many dockerbeat as docker daemon**
* or should we configure **one dockerbeat to monitor many docker daemons** (`socket` configuration property could be modified to `sockets` and be an array of sockets)

This case could append when there is many docker daemons deployed on several machines and listening on TCP. It could be usefull to centralize stats collect on one dedicated host with only one dockerbeat instance, pulling many TCP sockets.

Related to #58 (to identify the docker daemon) and #58 (to allow remote connection to docker daemon).

**Comment by marminthibaut** [comment]
After a bit of thought, i think dockerbeat has to stay as simple as possible and should not allow multiple daemon monitoring.

Any other opinion?

**Comment by ruflin** [comment]
In general I think each beat should be as local as possible, means running on the same machine if possible. So in case there are potentially multiple docker daemons on one machine, I would be +1 to support it. But if in general there is one docker daemon per machine, I would suggest to install one beat per machine and keep it as simple as possible.

**Comment by gpolaert** [comment]
I'm wondering if there is a place for swarm and dockerbeat. Swarm can provide some information about nodes, ip, cpu, and so on, plus containers
2 thoughts:
* Can we handles beats via swarm/dockerbeat? Is it interesting (not sure)?
* Do we have to provide a json swarm event if the socket is a instance of swarm node?

**Comment by marminthibaut** [comment]
Issue conclusion: keep dockerbeat as local as possible to the docker daemon, so 1 dockerbeat = 1 docker daemo
