### ISSUE TITLE
Set some common parameters via environment

### ISSUE THREAD

**Issue by ddrozdov** [Ingensi/dockerbeat#68]
Instead of creating custom a config file just to set a non-default elasticsearch port for example, it would be more convenient to be able to set it via the environment variables.
Like this:
```
docker run -d ... -e HOST=192.168.0.1 -e PORT=9999
```
See the example of this approach here: https://github.com/athieriot/docker-elastic-topbeat

I suggest to support this list of variables: PERIOD, HOST, PORT, SHIPPER_NAME, SHIPPER_TAGS.

**Comment by tsg** [comment]
Just a heads up, libbeat now supports setting env variables in the configuration files: https://github.com/elastic/beats/pull/715

So dockerbeat could get this automatically by updating its libbeat version.

**Comment by marminthibaut** [comment]
Oh i try it right away!

**Comment by erwanncloarec** [comment]
I just tried, it does not seem to work with the current dockerbeat version.

We have to update libbeat for that
