### ISSUE TITLE
Add dockerbeat to AUR repo

### ISSUE THREAD

**Issue by gpolaert** [Ingensi/dockerbeat#78]
Could we push dockerbeat to AUR repo (for Arch distrib) like topbeat, filebeat and so on ?

**Comment by marminthibaut** [comment]
Do you want to become an active contributor?

:+1:

**Comment by HipsterWhale** [comment]
I'll do it

**Comment by gpolaert** [comment]
Thanks :)

**Comment by HipsterWhale** [comment]
done : https://aur.archlinux.org/packages/dockerbeat/ :)

**Comment by marminthibaut** [comment]
Well done! Thx
