### ISSUE TITLE
Logstash output?

### ISSUE THREAD

**Issue by tymofii-polekhin** [Ingensi/dockerbeat#79]
Didn't find this one in README, are we able to output to logstash?

**Comment by marminthibaut** [comment]
Of course, this feature is not related to dockerbeat but to libbeat.

Configure the output section of `dockerbeat.yml`: https://github.com/Ingensi/dockerbeat/blob/develop/etc/dockerbeat.yml#L104

You can set elasticsearch, logstash or file as beat output.

**Comment by tymofii-polekhin** [comment]
Cool, thanks!

**Comment by marminthibaut** [comment]
Enjoy dockerbeat! Do not hesitate to leave questions and comments

**Comment by patrick-bark** [comment]
+1 awesome, perhaps should be added to the docs. This is a major plus over your competitors (cadvisor). Thanks

**Comment by rkmresh** [comment]
Hi, Is there any sample dockerbeat.yml for logstash?
I try to output to logstash I don't see any output. But output to elasticsearch and file is working.
Can you help me on this? Thank you.
