### ISSUE TITLE
Improve README content

### ISSUE THREAD

**Issue by marminthibaut** [Ingensi/dockerbeat#82]
* add a TLDR
* rewrite some parts
* etc.

**Comment by marminthibaut** [comment]
@HipsterWhale Does all update are treated by the #83 #84 PRs?

**Comment by HipsterWhale** [comment]
No, still missing the TL;DR, I'll do it right now

**Comment by marminthibaut** [comment]
I think that we should improve the README.

For example, @patrick-bark suggested to add doc about outputs in #79
