### ISSUE TITLE
Issue starting dockerbeat with ES_HOSTS

### ISSUE THREAD

**Issue by jarkomes** [Ingensi/dockerbeat#89]
Hello,

We are getting an error when starting dockerbeat with the ES_HOSTS parameter in our docker run (our elasticsearch cluster is not running in docker and on other machines, so we use ES_HOSTS):
docker run --net bridge -m 0b --detach=true -e ES_HOSTS=xxx.xxxxxx.xxx.domain.tld -v /var/run/docker.sock:/var/run/docker.sock --name dockerbeat-app00 ingensi/dockerbeat:develop

Start error: loading config file error: YAML config parsing failed on dockerbeat.yml: yaml: unmarshal errors:
  line 29: cannot unmarshal !!str `xxx-xx...` into []string. Exiting.

panic: close of nil channel

goroutine 1 [running]:
github.com/ingensi/dockerbeat/beat.(*Dockerbeat).Stop(0xc82014ae10)
	/go/src/github.com/ingensi/dockerbeat/beat/Dockerbeat.go:122 +0x24
github.com/elastic/beats/libbeat/beat.(*Beat).Stop(0xc82014aea0)
	/go/src/github.com/ingensi/dockerbeat/Godeps/_workspace/src/github.com/elastic/beats/libbeat/beat/beat.go:262 +0x77
github.com/elastic/beats/libbeat/beat.Run(0x95e790, 0xa, 0x955710, 0xb, 0x7fe7940a51b8, 0xc82014ae10, 0x0, 0x0)
	/go/src/github.com/ingensi/dockerbeat/Godeps/_workspace/src/github.com/elastic/beats/libbeat/beat/beat.go:127 +0xd0
main.main()
	/go/src/github.com/ingensi/dockerbeat/main.go:14 +0xa4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

Kr,
Jarko

**Comment by marminthibaut** [comment]
I @jarkomes ,

Try to set ES_HOST as following: `ES_HOST=[\"xxx:9200\"]

There were a mistake in the README file, I just updated it 30 minute ago ;)

**Comment by marminthibaut** [comment]
Please leave a comment if it works, then I'll close the issue

**Comment by jarkomes** [comment]
Works! Thanks again for your assistance.
